# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TenKClub' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  # Pods for TenKClub

  #target 'TenKClub-tvOSTests' do
  #inherit! :search_paths
    # Pods for testing
  #end

  target 'TenKClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TenKClub-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TenKClub-tvOS

  target 'TenKClub-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


